version: "3.8"
services:
  postgres:
    image: postgres:14-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mudasir
      POSTGRES_DB: api
    ports:
      - "5432:5432"
    volumes:
      - db:/var/lib/postgresql/data

  backend:
    build: .
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://root:secret@postgres:5432/api
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: ["npm", "run", "dev"]

volumes:
  db:
